-- +goose Up
-- +goose StatementBegin

CREATE TYPE order_status AS ENUM ('new', 'awaiting_payment', 'failed', 'payed', 'cancelled');

CREATE TABLE IF NOT EXISTS warehouse (
     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     sku bigint NOT NULL,
     stock INT NOT NULL,
     created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
     deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS orders (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id bigint NOT NULL,
      status order_status NOT NULL,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warehouse_orders (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      warehouse_id bigint NOT NULL CONSTRAINT warehouse_orders_wh_fk REFERENCES warehouse(id),
      order_id bigint NOT NULL CONSTRAINT warehouse_orders_ord_fk REFERENCES orders(id),
      cnt INT NOT NULL,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      deleted_at timestamptz
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
