-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS outbox (
     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     topic varchar NOT NULL,
     args jsonb NOT NULL,
     created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
     deleted_at timestamptz
);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE outbox;
-- +goose StatementEnd
