{
 "title": "checkout",
 "time": { "from": "2023-04-10T18:06:52.647Z", "to": "2023-04-10T18:31:23.007Z" },
 "panels": [
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Response time quantiles by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \nsum(rate(checkout_grpc_histogram_response_time_seconds_bucket[10s])) by (le, status))",
     "legendFormat": "0.9q {{status}}"
    }
   ]
  },
  {
   "title": "Response time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \nsum(rate(checkout_grpc_histogram_response_time_seconds_bucket[10s])) by (le))",
     "legendFormat": "0.9q"
    },
    {
     "expr": "histogram_quantile(0.99, \nsum(rate(checkout_grpc_histogram_response_time_seconds_bucket[10s])) by (le))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.8, \nsum(rate(checkout_grpc_histogram_response_time_seconds_bucket[10s])) by (le))",
     "legendFormat": "0.8q"
    }
   ]
  },
  {
   "title": "Response status per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(checkout_grpc_responses_total[10s])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "incoming requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(checkout_grpc_requests_total[10s])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}