global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s # Evaluate rules


rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: false
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "checkout"
    honor_timestamps: false
    static_configs:
      - targets:
          - "checkout:8090"
  - job_name: "loms"
    honor_timestamps: false
    static_configs:
      - targets:
          - "loms:8091"
  - job_name: "notifications"
    honor_timestamps: false
    static_configs:
      - targets:
          - "notifications:8092"