web-port: 8080
metrics-port: 8090
service-name: checkout
env: prod
services:
    loms:
        url: loms:8081
    products-service:
        token: DnaNIiL3NecPHwgxLzGqEhUL
        url: route256.pavl.uk:8082